env:
  es6: true
  node: true
  # browser: false
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
extends:
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:prettier/recommended'
root: true
# ignorePatterns: []
